
%% Script to plot Figure 8a

% ------------------------------------------------------------------------%
% Copyright 2017 Regents of the University of California

% Redistribution and use in source and binary forms, with or without
% modification, are permitted provided that the following conditions
% are met:

% 1. Redistributions of source code must retain the above copyright
%    notice, this list of conditions and the following disclaimer.

% 2. Redistributions in binary form must reproduce the above copyright
%    notice, this list of conditions and the following disclaimer in the
%    documentation and/or other materials provided with the distribution.

% 3. Neither the name of the copyright holder nor the names of its
%    contributors may be used to endorse or promote products derived
%    from this software without specific prior written permission.

% THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
% "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
% LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
% A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
% HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
% SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
% LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
% DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
% THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
% (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
% OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
% ------------------------------------------------------------------------%


rerunsims=0;
% 1 - rerun the simulations to generate data, then plot
% 0 - load previously saved data, then plot


%% load LP results for packet switch and RotorNet

filename1='LP_PsBW_N16_93.mat';
filename2='LP_RotorBW_N=16_93.mat';

load(filename1);
NN=25;
PBWav=sum(BWp,2)/Nreal;
[NNp,~]=size(PBWav);
PBWav=[PBWav;(N-1)*ones(NN-NNp,1)];

load(filename2);

%% run/load Matlab simulation of RotorLB

filename3='RotorLB_N=16_93.mat';

path=[pwd '\RotorNet_model\'];

if rerunsims==1
    cd RotorNet_model
    Main_RotorLB_16();
    cd ..
end;

% NOTE: this .mat file is generated by running the function: [pwd '\RotorNet_model\Main_RotorLB_16.m']
load([path filename3]);

%% plot

F=16; % fontsize
LW=2; % linewidth

figure;
hold on;

% --- LP solver
hlp=plot((Nflows0)/(Nflows0(end)),RBWLP./PBWav,'-ko','linewidth',LW,'markersize',8);

% --- matching fill factor
hff=plot([0 1],[(N-1)/N (N-1)/N],'--r','linewidth',LW);

% --- RotorLB
hrlb=plot(Nflows0/Nflows0(end),sum(BWr(:,:,4),2)./(Nreal*PBWav),'color',.7*[0 1 1],'linewidth',LW,'marker','^','markersize',8);

% --- One-hop forwarding
h1hop=plot([1/(N^2-N) 1],[1/N (N-1)/N],'--k','linewidth',LW);

% --- 3:1 Fat Tree
h31=plot([0 1],1/3*[1 1],':m','linewidth',LW);

% legend
hleg=legend([hff hlp hrlb h1hop h31], ...
    'Matching fill factor','LP solver','RotorLB','One-hop forwarding','Ideal 3:1 Fat Tree');
hleg.Location='southeast';
hleg.FontSize=16;

ax=gca;
ax.YTick=(0:.1:1);
ax.YTickLabel={'0','','0.2','','0.4','','0.6','','0.8','','1'};

grid on;
box on;
xlim([0 1]);
ylim([0 1]);
set(gca,'fontsize',F);
xlabel('Traffic density');
ylabel('Relative aggregate throughput');


ax.XColor=[0 0 0];
ax.YColor=[0 0 0];
ax.GridColor=[0 0 0];
ax.MinorGridColor=[0 0 0];
ax.GridAlpha=.2;

outerpos = ax.OuterPosition;
ti = ax.TightInset; 
left = outerpos(1) + ti(1);
bottom = outerpos(2) + ti(2);
ax_width = outerpos(3) - ti(1) - ti(3);
ax_height = outerpos(4) - ti(2) - ti(4);
ax.Position = [left bottom ax_width ax_height];

fig = gcf;
fig.PaperPositionMode = 'auto';
fig_pos = fig.PaperPosition;
fig.PaperSize = [fig_pos(3) fig_pos(4)];


%%






